name: genotyphi unit testing

on: [push]

jobs:
  unit-testing:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
        #python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install -y samtools bcftools bowtie2
    - name: Get data
      run: |
        wget 'https://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=AL513382.1&rettype=fasta' -O tmp.fasta
        cat tmp.fasta | perl -lane 'last if($seenChrom); if(/>/){s/.+/>AL513382.1/; $seenChrom++;} print;' > CT18.fasta
        grep -A 1 ">" CT18.fasta
        
        
